# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.0'
    hooks:
    -   id: codespell
