[source.crates-io]
# Temporarily disable vendoring override for new exporter build. Re-enable with vendor directory.
# replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
