#!/usr/bin/env python3
#
#  Copyright (c) 2015 - 2025 Intel Corporation
#  SPDX-License-Identifier: BSD-3-Clause
#

"""
This integration test verifies that region classification neural nets and frequency
recommendation maps can be autogenerated and that the ffnet agent is functional.
"""
import json
import sys
import unittest
import os
import glob
from pathlib import Path
import pandas as pd
import numpy as np
import shutil
from types import SimpleNamespace

import geopmpy.agent
import geopmpy.io

from integration.apps.geopmbench import geopmbench
from integration.apps.parres import parres

from integration.test import util
from integration.test import geopm_test_launcher

from integration.experiment import machine
from integration.experiment.ffnet import ffnet
from integration.experiment.ffnet import neural_net_sweep
from integration.experiment.ffnet import gen_hdf_from_fsweep
from integration.experiment.ffnet import gen_neural_net
from integration.experiment.ffnet import gen_region_parameters

@util.skip_unless_do_launch()

class TestIntegration_ffnet(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        """
        Setup applications, execute, and set up class variables.
        """
        mach = machine.init_output_dir('.')
        cls._skip_launch = not util.do_launch()
        cls._test_name = 'test_ffnet_nn_scripts'
        #TODO: Get rid of this
        cls._do_all = False
        cls._do_gen_nn = False

        ########################
        # CPU Neural Net Sweep #
        ########################

        # Grabbing system frequency parameters for experiment frequency bounds
        # Choosing the maximum many core frequency to remove redundant frequency sweep values
        cls._cpu_max_freq = mach.frequency_max_many_core()
        cls._cpu_min_freq = mach.frequency_min()
        cls._cpu_freq_step = 2 * mach.frequency_step()

        cls._node_count = 1
        cls._run_count = 0

        # Setup Common Args
        cls._nn_sweep_dir = Path(os.path.join(Path.cwd(),'test_ffnet', 'nn_frequency_sweep'))
        cpu_fsweep_experiment_args = SimpleNamespace(
            output_dir=cls._nn_sweep_dir,
            node_count=cls._node_count,
            max_frequency = cls._cpu_max_freq,
            min_frequency = cls._cpu_min_freq,
            step_frequency = cls._cpu_freq_step,
            trial_count = 1,
            cool_off_time = 3,
            run_max_turbo = False
        )

        experiment_cli_args=['--geopm-ctl=process']

        # Configure the CPU test application - geopmbench
        cpu_test_app_params = {
            'spin_bigo': 1.0,
            'sleep_bigo': 1.0,
            'dgemm_bigo': 12.0,
            'stream_bigo': 3.0,
            'loop_count': 30
        }
        cls._app_regions = {}
        #TODO: Get hashes later from a report and assemble this info
        cls._app_regions['cpu'] = {'spin':"geopmbench-0x120a248f",
                                   'sleep':"geopmbench-0x0f33c2ac",
                                   'dgemm':"geopmbench-0xa12de8ee",
                                   'stream':"geopmbench-0xf0e9be1c"}

        bench_conf = geopmpy.io.BenchConf(cls._test_name + '_app.config')
        bench_conf.set_loop_count(cpu_test_app_params['loop_count'])
        for region in cls._app_regions['cpu']:
            bench_conf.append_region(region, cpu_test_app_params[f"{region}_bigo"])
        bench_conf.write()

        cpu_app_conf = geopmbench.GeopmbenchAppConf(os.path.abspath(bench_conf.get_path()), 1)

        #Launch CPU Frequency Sweeps for NN Generation - geopmbench
        if cls._do_all:
            cls.launch_helper(cls, neural_net_sweep, cpu_fsweep_experiment_args, cpu_app_conf, experiment_cli_args)

        ########################
        # GPU Neural Net Sweep #
        ########################

        # Checking if a gpu is present on the system and parres is built. If so, ensuring
        # that a reasonable number of frequency steps is taken for NN frequency sweep
        # as some GPUs have very fine frequency steps

        cls._do_gpu = False
        cls._num_gpu = mach.num_gpu()
        parres_basepath = os.path.join(os.path.dirname(
                              os.path.dirname(os.path.realpath(__file__))),
                                              "apps/parres/Kernels/Cxx11")
        if cls._num_gpu > 0 and os.path.exists(parres_basepath):
            cls._do_gpu = True
            cls._gpu_freq_min = mach.gpu_frequency_min()
            cls._gpu_freq_max = cls._gpu_frequency_max()
            cls._gpu_freq_step = mach.gpu_frequency_step()
            course_step = round((cls._gpu_frequency_max() - mach.gpu_frequency_min())/4)
            if course_step > cls._gpu_freq_step:
                cls._gpu_freq_step = course_step

            #GPU Frequency Sweeps for NN Generation - parres
            gpu_fsweep_experiment_args = SimpleNamespace(
                output_dir=cls._nn_sweep_dir,
                node_count=cls._node_count,
                max_gpu_frequency = cls._gpu_max_freq,
                min_gpu_frequency = cls._gpu_min_freq,
                step_gpu_frequency = cls._gpu_freq_step,
                trial_count = 1,
                run_max_turbo = False
            )

            # Configure the GPU test application - parres dgemm/nstream
            gpu_experiment_args = SimpleNamespace(
                node_count=cls._node_count,
                trial_count = 1,
                cool_off_time=3,
                parres_cores_per_node=None,
                parres_gpus_per_node=None,
                parres_cores_per_rank=1,
                parres_init_setup=None,
                parres_exp_setup=None,
                parres_teardown=None,
                parres_args=None,
                output_dir=cls._nn_sweep_dir,
                min_gpu_frequency = cls._gpu_freq_min,
                max_gpu_frequency = cls._gpu_freq_max,
                step_gpu_frequency = cls._gpu_freq_step
            )

            cls._app_regions['gpu'] = {'dgemm':'parres_dgemm-0xDEADBEEF',
                                       'nstream':'parres_nstream-0xDEADBEEF'}
            #Get correct parres executables and set up app conf
            if util.get_service_config_value('enable_nvml') == '1':
                app_exec_names = ["dgemm-mpi-cublas", "nstream-mpi-cuda"]
                app_confs = [parres.create_dgemm_appconf_cuda(mach, experiment_args),
                             parres.create_nstream_appconf_cuda(mach, experiment_args)]
            elif util.get_service_config_value('enable_levelzero') == '1':
                app_exec_names = ["dgemm-onemkl", "nstream-onemkl"]
                app_confs = [parres.create_dgemm_appconf_oneapi(mach, experiment_args),
                             parres.create_nstream_appconf_oneapi(mach, experiment_args)]
            for app in app_exec_names:
                app_path = os.path.join(parres_basepath, app)
                if os.path.exists(app_path):
                    parres_app_paths.append(app_path)

            #If no parres executables exist, error
            if len(parres_app_paths) == 0:
                self.fail("No parres dgemm/nstream executables were found. Cannot test GPU.")

            #Launch GPU Frequency Sweeps for NN Generation - parres dgemm / nstream
            if cls._do_all:
                for parres_app_conf in app_confs:
                    cls.launch_helper(neural_net_sweep, gpu_experiment_args, parres_app_conf, [], None)


        # Set up HDF/neural net file info
        cls._nn_output_prefix = "test_ffnet/test_nn"
        cls._nn_description = "test description"
        cls._nn_regions_ignore = ["geopmbench-0x68317b3c", "geopmbench-unmarked"]
        cls._nn_stats_hdf = f"{cls._nn_output_prefix}_stats.h5"
        cls._nn_trace_hdf = f"{cls._nn_output_prefix}_traces.h5"
        cls._nn_out = f"{cls._nn_output_prefix}_nn"
        cls._nn_fmap_out = f"{cls._nn_output_prefix}_fmap"

        if cls._do_gen_nn:
            # Generate h5s
            gen_hdf_from_fsweep.main(cls._nn_output_prefix, str(cls._nn_sweep_dir), ",".join(cls._nn_regions_ignore))
            # Generate neural nets
            gen_neural_net.main(cls._nn_trace_hdf, cls._nn_out)

            # Generate frequency region map
            gen_region_parameters.main(cls._nn_fmap_out, cls._nn_stats_hdf)

        ###################
        # FFNet Agent Run #
        ###################

        # Configure the ffnet agent
        cls._agent = 'ffnet'

        #TODO: Replace
        cls._perf_energy_biases = [0, 0.5, 1]
        cls._ffnet_dir = Path(os.path.join(Path.cwd(), 'test_ffnet', 'ffnet'))

        cls._cpu_nn_path = str(Path.cwd()) + "/" + cls._nn_out + "_cpu.json"
        cls._cpu_fmap_path = str(Path.cwd()) + "/" + cls._nn_fmap_out + "_cpu.json"

        # Configure the CPU test application - geopmbench
        # TODO: Set up GPU run, too, if there's GPU on system and parres
        cls._loop_count = 2
        cls._test_app_params = {
            'spin': 1.0,
            'sleep': 1.0,
            'dgemm': 2.0,
            'stream': 2.0,
        }

        bench_conf = geopmpy.io.BenchConf(cls._test_name + '_app.config')
        bench_conf.set_loop_count(cls._loop_count)
        for region in cls._test_app_params:
            bench_conf.append_region(region, cls._test_app_params[region])
        bench_conf.write()

        ffnet_app_conf = geopmbench.GeopmbenchAppConf(os.path.abspath(bench_conf.get_path()), 1)

        for phi in cls._perf_energy_biases:
            ffnet_dir = Path(os.path.join(cls._ffnet_dir, f'phi{phi}'))
            ffnet_experiment_args = SimpleNamespace(
                output_dir = ffnet_dir,
                perf_energy_bias = phi,
                cpu_nn_path = cls._cpu_nn_path,
                cpu_fmap_path = cls._cpu_fmap_path,
                node_count = cls._node_count,
                trial_count = 1,
                cool_off_time = 3,
                enable_traces = True,
                enable_profile_traces = False,
            )

            cls.launch_helper(cls, ffnet, ffnet_experiment_args, ffnet_app_conf, experiment_cli_args)

        # Get traces and reports
        cls._trace_path = glob.glob(str(cls._ffnet_dir) + "/*phi*/*trace*")
        cls._trace_data = {}
        cls._report_data = {}
        for phi in cls._perf_energy_biases:
            #Get traces
            trace_path = glob.glob(str(cls._ffnet_dir) + f"/phi{phi}/*trace*")
            trace = geopmpy.io.AppOutput(traces=trace_path[0])
            cls._trace_data[phi] = trace.get_trace_data()

            #Get report
            report_path = glob.glob(str(cls._ffnet_dir) + f"/phi{phi}/*report")
            cls._report_data[phi] = geopmpy.io.RawReport(report_path[0])

        ###########
        # Helpers #
        ###########

    #Used to calculate region probabilities
    def sigmoid(self, x):
        return 1/ (1 + np.exp(-x))

    def softmax(self, x):
        e_x = np.exp(x - np.max(x))
        return e_x / e_x.sum()

    #Check if JSON is valid (used in tests below)
    def get_json(self, json_file):
        try:
            json_parsed = json.load(json_file)
        except ValueError:
            json_parsed = None
        return json_parsed

    #Get region name : region hash mapping
    def get_region_map(self):
        report = self._report_data[self._perf_energy_biases[0]]
        hostname = report.host_names()[0]
        region_names = report.region_names(hostname)
        region_map = {}

        for region in region_names:
            region_map[region] = report.raw_region(hostname, region)["hash"]

        return region_map

    #Launch Helper for multiple job launches
    def launch_helper(self, experiment_type, experiment_args, app_conf, experiment_cli_args):
        if not self._skip_launch:
            self._run_count += 1

            output_dir = experiment_args.output_dir
            if output_dir.exists() and output_dir.is_dir():
                shutil.rmtree(output_dir)

            experiment_type.launch(app_conf=app_conf, args=experiment_args,
                                   experiment_cli_args=experiment_cli_args)


    def test_hdf_generation(self):
        """
        Test that the hdfs were generated properly from frequency sweeps

        Pass Criteria:
            - Desired stats columns are present
            - Desired trace columns are present
        """
        stats_hdf = pd.read_hdf(self._nn_stats_hdf)
        trace_hdf = pd.read_hdf(self._nn_trace_hdf)

        cpu_stats_columns = ["node", "app-config", "runtime (s)",
                             "cpu-frequency", "package-energy (J)"]
        gpu_stats_columns = ["gpu-frequency", "gpu-energy (J)"]

        cpu_trace_columns = ['node', 'app-config', 'TIME', 'CPU_POWER-package-0',
                             'CPU_FREQUENCY_STATUS-package-0',
                             'MSR::UNCORE_PERF_STATUS:FREQ-package-0',
                             'MSR::QM_CTR_SCALED_RATE-package-0',
                             'CPU_INSTRUCTIONS_RETIRED-package-0',
                             'CPU_CYCLES_THREAD-package-0',
                             'CPU_ENERGY-package-0',
                             'MSR::APERF:ACNT-package-0',
                             'MSR::PPERF:PCNT-package-0',
                             'MSR::PPERF:PCNT-package-0']

        gpu_trace_columns = ['GPU_CORE_FREQUENCY_STATUS-gpu-0',
                             'GPU_POWER-gpu-0',
                             'GPU_UTILIZATION-gpu-0',
                             'GPU_CORE_ACTIVITY-gpu-0',
                             'GPU_UNCORE_ACTIVITY-gpu-0']

        #Check for desired stats columns
        for col in cpu_stats_columns:
            self.assertTrue(col in stats_hdf)
        if self._do_gpu:
            for col in gpu_stats_columns:
                self.assertTrue(col in stats_hdf)
        else:
            for col in gpu_stats_columns:
                self.assertFalse(col in stats_hdf)

        #Check for desired trace columns
        for col in cpu_trace_columns:
            self.assertTrue(col in trace_hdf)
        if self._do_gpu:
            for col in gpu_trace_columns:
                self.assertTrue(col in trace_hdf)
        else:
            for col in gpu_trace_columns:
                self.assertFalse(col in trace_hdf)

    def test_nn_generation(self):
        """
        Test that the neural net was generated as expected

        Pass Criteria:
            - The neural net file contains valid json
            - The desired fields are present
            - Expected regions are present (from application region hashes)
            - Ignored regions are not present
        """
        nn_files = {"cpu":f"{self._nn_out}_cpu.json"}
        if self._do_gpu:
            nn_files["gpu"] = f"{self._nn_out}_gpu.json"

        nn_fields = ["description", "delta_inputs", "signal_inputs", "trace_outputs", "layers"]

        nn_jsons = {}
        for domain in nn_files:
            fp = open(nn_files[domain], "r")
            nn_jsons[domain] = self.get_json(fp)

            #Check that the neural net file contains valid json
            self.assertTrue(nn_jsons[domain] is not None)

            #Check that the desired fields are present
            for nn_field in nn_fields:
                self.assertTrue(nn_field in nn_jsons[domain])

            #Check that the appropriate regions are present/ignored in trace_output
            for region in self._app_regions[domain]:
                if self._app_regions[domain][region] in self._nn_regions_ignore:
                    self.assertFalse(self._app_regions[domain][region] in nn_jsons[domain]["trace_outputs"])
                else:
                    self.assertTrue(self._app_regions[domain][region] in nn_jsons[domain]["trace_outputs"])
            fp.close()

    def test_freqmap_generation(self):
        """
        Test that the region frequency map was generated as expected

        Pass Criteria:
            - The fmap file contains valid json
            - Desired regions are present/ignored in json file
            - The frequency values for each region decrease monotonically with phi
            - For phi=0, sleep region's recommended frequency is not greater than
              dgemm's recommended frequency
            - For phi=1, spin's recommended frequency is less than dgemm's
              recommended frequency
            - Sleep has a stronger frequency throttle between phi=0 to phi=1
              than DGEMM does.
        """
        #Region frequency map JSONs (with/without GPUs)
        fmap_files = {"cpu":f"{self._nn_fmap_out}_cpu.json"}
        fp = {}
        if self._do_gpu > 0:
            fmap_files["gpu"] = f"{self._nn_fmap_out}_gpu.json"

        fmap_jsons = {}
        for domain in fmap_files:
            fp[domain] = open(fmap_files[domain], "r")
            fmap_jsons[domain] = self.get_json(fp[domain])

            #Check that the region frequency map file contains valid json
            self.assertTrue(fmap_jsons[domain] is not None)

            #Check that desired regions are present/ignored in json file
            for region in self._app_regions[domain]:
                if self._app_regions[domain][region] in self._nn_regions_ignore:
                    self.assertFalse(self._app_regions[domain][region] in fmap_jsons[domain])
                else:
                    self.assertTrue(self._app_regions[domain][region] in fmap_jsons[domain])

            #Check that frequency values decrease monotonically with phi
            for region in fmap_jsons[domain]:
                freq_list = fmap_jsons[domain][region]
                self.assertTrue(all(x>=y for x,y in zip(freq_list, freq_list[1:])))

        #Check that CPU region frequency for sleep is <= dgemm at phi=0 (could both be fmax)
        self.assertTrue(fmap_jsons["cpu"][self._app_regions['cpu']['sleep']][0] <= fmap_jsons["cpu"][self._app_regions['cpu']['dgemm']][0])

        #Check that CPU region frequency for spin is < dgemm at phi=1 (strictly)
        self.assertTrue(fmap_jsons["cpu"][self._app_regions['cpu']['stream']][-1] < fmap_jsons["cpu"][self._app_regions['cpu']['dgemm']][-1])

        #Check that sleep's frequency decrease (phi=0 to phi=1) is
        #greater than dgemm's frequency decrease (phi=0 to phi=1)
        df_sleep = fmap_jsons["cpu"][self._app_regions['cpu']['sleep']][0] - fmap_jsons["cpu"][self._app_regions['cpu']['sleep']][-1]

        df_dgemm = fmap_jsons["cpu"][self._app_regions['cpu']['dgemm']][0] - fmap_jsons["cpu"][self._app_regions['cpu']['dgemm']][-1]
        self.assertTrue(df_sleep >= df_dgemm)
        fp['cpu'].close()

        if self._do_gpu is True:
            #Check that parres nstream's frequency at phi=1 is less than dgemm's frequency at phi=1
            dgemm_freq = fmap_jsons["gpu"][self._app_regions['gpu']['dgemm']][-1]
            nstream_freq = fmap_jsons["gpu"][self._app_regions['gpu']['nstream']][-1]
            assertTrue(dgemm_freq > nstream_freq)
            fp['gpu'].close()

    def test_no_harm(self):
        """
        Test that the phi=0 decisions do not significantly lower performance

        Pass Criteria:
            - FoM is within 95% of standard monitor
            - For each region, phi=0 runtime is within 95% of max freq run
            - For each region, phi=0 power is at most the same as max freq run
        """

    def test_phi(self):
        """
        Test the perf-energy-bias knob

        Pass Criteria:
            - Phi=0 FoM >= Phi=1 FoM
            - For each region, phi=0 runtime >= phi=1 runtime
            - For each region, phi=0 mean power >= phi=1 mean power
            - For each region, phi=0 frequency >= phi=1 frequency
        """
    def test_region_accuracy(self):
        """
        Test that the ffnet agent identifies geopmbench regions accurately

        Pass Criteria:
            - For a given REGION_HASH, 95% of trace lines indicate >=95%
              probability of being in the correct identified region
        """
        return True
        # Calculate probabilities per phi
#        for datum in cls._trace_data:
#            cols = [col for col in df if col.startswith("geopmbench")]
#
#            subset = datum[list(datum.filter(regex='geopmbench'))]
#            probabilities = subset.apply(self.sigmoid)
#            probabilities['REGION_HASH'] = datum['REGION_HASH']
#
#            # Count lines where probability of correct ID is >95%
#            for region in self._app_regions:
#                region_hash = hex(self._app_regions[region])
#                df = probabilities[probabilities["REGION_HASH"] == region_hash]
#                samples_total = len(df)
#                samples_good = len(df[df[f"geopmbench-{region_hash}_{geopmdpy.topo.DOMAIN_PACKAGE}_0"] > 0.95])
#                self.assertTrue(samples_good/samples_total > 0.95)
#
    def test_frequency_selection(self):
        """
        Test that the frequency selection made by ffnet aget is reasonable.

        Pass Criteria:
            - For a given REGION_HASH and phi value, the average frequency
              control is within 5% of fmap's target frequency
        """

        return True

if __name__ == '__main__':
    # Call do_launch to clear non-pyunit command line option
    util.do_launch()
    unittest.main()
