#!/usr/bin/env python3

#  Copyright (c) 2015 - 2023, Intel Corporation
#  SPDX-License-Identifier: BSD-3-Clause
#

import sys
from geopmdpy.access import main

if __name__ == '__main__':
    sys.exit(main())
