apiVersion: v1
kind: Pod
metadata:
   name: geopm-service-pod
spec:
   restartPolicy: Never
   shareProcessNamespace: true
   containers:
   - name: geopm-server
     image: cmcantal/geopm-service:tumbleweed
     imagePullPolicy: Always
     securityContext:
       privileged: true
     volumeMounts:
     - name: geopm-mount
       mountPath: /run/geopm-service
     - name: cpu-mount
       mountPath: /dev/cpu
     - name: tmp-mount
       mountPath: /tmp
     command: ['/usr/bin/sh', '-c', 'chmod 711 /run/geopm-service; geopmread >> /etc/geopm-service/0.DEFAULT_ACCESS/allowed_signals; groupadd -g 10001 client; useradd -g 10001 -u 10001 client; geopmd --grpc']
   - name: geopm-client
     image: cmcantal/geopm-service:tumbleweed
     imagePullPolicy: Always
     securityContext:
       privileged: false
       allowPrivilegeEscalation: false
       readOnlyRootFilesystem: true
       runAsNonRoot: true
       runAsUser: 10001
       runAsGroup: 10001
     volumeMounts:
     - name: geopm-mount
       mountPath: /run/geopm-service
     - name: tmp-mount
       mountPath: /tmp
     command: ['/usr/bin/sh', '-c', 'sleep 5; for ss in $(geopmread | grep -v SERVICE::); do printf %s= $ss ; if geopmread $ss board 0 2>/dev/null; then echo $ss board 0 >> /tmp/geopmsession-requests.txt; else echo "UNAVAILABLE"; fi; done; for rr in $(cat /tmp/geopmsession-requests.txt | cut -d" " -f 1); do printf %s, $rr; done; echo; geopmsession -t100 -p1 < /tmp/geopmsession-requests.txt; rm /tmp/geopmsession-requests.txt; sleep 3600']
   volumes:
   - name: geopm-mount
     emptyDir: {}
   - name: tmp-mount
     emptyDir: {}
   - name: cpu-mount
     hostPath:
       path: /dev/cpu
