#!/usr/bin/env python3
#
#  Copyright (c) 2015 - 2025 Intel Corporation
#  SPDX-License-Identifier: BSD-3-Clause
#

import sys
import geopmpy.launcher

if __name__ == '__main__':
    err = geopmpy.launcher.main()
    sys.exit(err)
