apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: tensorflow-mnist
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
    suspend: true
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: localhost:5000/tfmnist:0.1
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - mpirun
            args:
            - -np
            - "2"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -x
            - https_proxy=http://proxy.ch.intel.com:911/
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - /examples/tensorflow_mnist.py
            resources:
              limits:
                cpu: 1
                memory: 2Gi
    Worker:
      replicas: 2
      template:
        spec:
          initContainers:
          - image: dannosliwcd/geopm-service:0.0.7
            name: mpi-prefix
            #command: ['/usr/bin/sh', 'sleep', '60']
            command: ['/usr/bin/sh', '-c', 'echo "power cap:$USER_POWER_CAP"; for ss in $(geopmread | grep -v "::"); do if geopmread $ss board 0 >/dev/null; then echo $ss board 0 >> /tmp/geopmsession-requests.txt; fi; done; for rr in $(cat /tmp/geopmsession-requests.txt | cut -d" " -f 1); do printf %s, $rr; done; echo; geopmsession -t1e9 -p1 < /tmp/geopmsession-requests.txt; rm /tmp/geopmsession-requests.txt']
            resources:
              limits:
                #cpu: 1
                #memory: 1Gi
                intel.com/power: 500
            restartPolicy: Always
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 10001
              runAsGroup: 10001
            volumeMounts:
            - name: geopm-mount
              mountPath: /run/geopm
            - name: tmp-mount
              mountPath: /tmp
          volumes:
          - name: geopm-mount
            hostPath:
              path: /tmp/run-geopm
          - name: tmp-mount
            emptyDir: {}
          containers:
          - image: localhost:5000/tfmnist:0.1
            name: mpi-worker
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            env:
            - name: https_proxy
              value: "http://proxy.ch.intel.com:911/"
            resources:
              limits:
                cpu: 2
                memory: 4Gi