#!/usr/bin/env python3
#
#  Copyright (c) 2015 - 2022, Intel Corporation
#  SPDX-License-Identifier: BSD-3-Clause
#

import sys
import yaml
import json
import geopmpy.io

def convert_report_to_json(path):
    geopmpy.io.RawReport(path).dump_json(path + '.json')

if __name__ == '__main__':
    convert_report_to_json(sys.argv[1])
