#!/bin/bash
#  Copyright (c) 2015 - 2021, Intel Corporation
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#      * Redistributions of source code must retain the above copyright
#        notice, this list of conditions and the following disclaimer.
#
#      * Redistributions in binary form must reproduce the above copyright
#        notice, this list of conditions and the following disclaimer in
#        the documentation and/or other materials provided with the
#        distribution.
#
#      * Neither the name of Intel Corporation nor the names of its
#        contributors may be used to endorse or promote products derived
#        from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY LOG OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e
set -x

if [ $# == 0 ]; then
    BASE_BUILD_DIR=$PWD
    SERVICE_BUILD_DIR=$PWD/service
elif [ $# == 1 ]; then
    BASE_BUILD_DIR=$1
    SERVICE_BUILD_DIR=$1
else
    BASE_BUILD_DIR=$1
    SERVICE_BUILD_DIR=$2
fi

TMPDIR=$(mktemp -d)
mkdir -p ${TMPDIR}

rm -f MANIFEST

./autogen.sh
version=$(cat VERSION)

./copying_headers/test-license

pushd ${BASE_BUILD_DIR}
    rm -f geopm-$version.tar.gz
    if [ ! -f Makefile ]; then
        echo "Error:  No makefile in base directory, run configure" 1>&2 && false
    fi
    make dist
    mv geopm-$version.tar.gz ${TMPDIR}
popd
pushd $SERVICE_BUILD_DIR
    if [ ! -f Makefile ]; then
        echo "Error:  No makefile in service directory, run configure" 1>&2 && false
    fi
    rm -f geopm-service-$version.tar.gz
    make dist
    mv geopm-service-$version.tar.gz ${TMPDIR}
popd

pushd ${TMPDIR}
    tar -xvf geopm-$version.tar.gz
    pushd geopm-$version
        ./copying_headers/test-license --ignore-service
        if [ -d service ]; then
            echo "Error:  The service directory is created by base tarball" 1>&2 && false
        fi
        tar xvf ../geopm-service-$version.tar.gz
        mv geopm-service-$version service
        ./copying_headers/test-license
    popd
popd

echo rm -rf ${TMPDIR}
echo [ PASSED ] geopm v$version distribution contains all files and all files have license headers.
