{
 "title": "GEOPM Profile Report",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Energy",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "GPU_ENERGY_mean * 2.7777777777777777e-7",
     "legendFormat": "GPU Energy"
    },
    {
     "expr": "CPU_ENERGY_mean * 2.7777777777777777e-7",
     "legendFormat": "CPU Energy"
    },
    {
     "expr": "DRAM_ENERGY_mean * 2.7777777777777777e-7",
     "legendFormat": "DRAM Energy"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "description": "Total power consumed by all GPUs on host",
   "gridPos": { "h": 10, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "GPU_POWER_mean", "legendFormat": "GPU Power (mean)" },
    { "expr": "GPU_POWER_max", "legendFormat": "GPU Power (max)" },
    { "expr": "GPU_POWER_min", "legendFormat": "GPU Power (min)" },
    { "expr": "GPU_POWER_std", "legendFormat": "GPU Power (std)" }
   ]
  },
  {
   "title": "CPU Power",
   "type": "timeseries",
   "description": "Total power consumed by all CPUs on host",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "CPU_POWER_mean", "legendFormat": "CPU Power (mean)" },
    { "expr": "CPU_POWER_max", "legendFormat": "CPU Power (max)" },
    { "expr": "CPU_POWER_min", "legendFormat": "CPU Power (min)" },
    { "expr": "CPU_POWER_std", "legendFormat": "CPU Power (std)" }
   ]
  },
  {
   "title": "DRAM Power",
   "type": "timeseries",
   "description": "Total power consumed by all DRAM on host",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "DRAM_POWER_mean", "legendFormat": "DRAM Power (mean)" },
    { "expr": "DRAM_POWER_max", "legendFormat": "DRAM Power (max)" },
    { "expr": "DRAM_POWER_min", "legendFormat": "DRAM Power (min)" },
    { "expr": "DRAM_POWER_std", "legendFormat": "DRAM Power (std)" }
   ]
  }
 ]
}